version: "3"
services:
  backend:
    image: node:lts
    # build:
    #   args:
    #     - NODE_ENV=development
    environment:
      - NODE_ENV=development
    # ports:
    #   - "8080:8080"
    #   - "8081:8181"
    volumes:
      - ./backend/src:/src
      - ./backend/package.json:/package.json
      - ./backend/server.js:/server.js
    command:
      ['sh', '-cx', "npm i && npm run dev"]
    networks:
      public:
  frontend:
    image: node:lts
    working_dir: /code
    # build:
      # context: frontend
      # target: development
    ports:
      - "8127:8127"
    volumes:
      - ./frontend/src:/code/src
      - ./frontend/vite.config.ts:/code/vite.config.ts
      - ./frontend/tailwind.config.js:/code/tailwind.config.js
      - ./frontend/index.html:/code/index.html
      - ./frontend/package.json:/code/package.json
    depends_on: 
      - backend
    command: ['sh', '-cx', "npm install && npm run build && npm run dev"]
    networks:
      - public
networks:
  public:
